from mongoengine import *


class RewardsReceiptItem(EmbeddedDocument):
    barcode = StringField()
    description = StringField()
    finalPrice = StringField()
    itemPrice = StringField()
    needsFetchReview = BooleanField()
    partnerItemId = StringField()
    pointsPayerId = StringField()
    rewardsProductPartnerId = StringField()
    pointsNotAwardedReason = StringField()
    needsFetchReviewReason = StringField()
    userFlaggedDescription = StringField()
    rewardsGroup = StringField()
    originalMetaBriteBarcode = StringField()
    brandCode = StringField()
    competitorRewardsGroup = StringField()
    originalReceiptItemText = StringField()
    discountedItemPrice = StringField()
    itemNumber = StringField()
    targetPrice = StringField()
    pointsEarned = StringField()
    competitiveProduct = BooleanField()
    originalMetaBriteItemPrice = StringField()
    originalFinalPrice = StringField()
    deleted = BooleanField()
    priceAfterCoupon = StringField()
    metabriteCampaignId = StringField()
    originalMetaBriteQuantityPurchased = IntField()
    originalMetaBriteDescription = StringField()
    preventTargetGapPoints = BooleanField()
    quantityPurchased = IntField()
    userFlaggedBarcode = StringField()
    userFlaggedNewItem = BooleanField()
    userFlaggedPrice = StringField()
    userFlaggedQuantity = IntField()


class Receipt(Document):
    bonusPointsEarned = IntField()
    bonusPointsEarnedReason = StringField()
    createDate = DateTimeField()
    dateScanned = DateTimeField()
    finishedDate = DateTimeField()
    modifyDate = DateTimeField()
    pointsAwardedDate = DateTimeField()
    pointsEarned = StringField()
    purchaseDate = DateTimeField()
    purchasedItemCount = IntField()
    rewardsReceiptItemList = ListField(EmbeddedDocumentField(RewardsReceiptItem))
    rewardsReceiptStatus = StringField()
    totalSpent = StringField()
    userId = StringField()


class User(Document):
    active = StringField()
    createdDate = DateTimeField()
    lastLogin = DateTimeField()
    role = StringField()
    signUpSource = StringField()
    state = StringField()


class Brand(Document):
    barcode = StringField()
    brandCode = StringField()
    category = StringField()
    categoryCode = StringField()
    cpg = StringField()
    name = StringField()
    topBrand = StringField()
